### ISSUE TITLE
Implement duration answer type

### ISSUE THREAD

**Issue by dariosalviwork** [ResearchStack/ResearchStack#228] opened 2016-04-29 14:24 UTC
as in:

```
{
      "guid":"db8d54db-c00e-4203-af71-2701253aa9e9",
      "identifier":"sleep_time",
      "prompt":"How many hours of sleep did you get last night?",
      "promptDetail":"Use the below scroll to indicate how long, in hours and minutes, you think you slept last night.",
      "constraints":{
        "rules":[

        ],
        "durationUnit":"minutes",
        "step":15,
        "dataType":"duration",
        "type":"DurationConstraints"
      },
      "uiHint":"timepicker",
      "type":"SurveyQuestion"
    }

```

**Comment by crayne** [comment] 2016-04-29 15:14
Duplicate of 216?

**Comment by dariosalviwork** [comment] 2016-04-29 15:16
not really, time picker is a time, duration is a range...

**Comment by crayne** [comment] 2016-04-29 16:00
in the RK GlucoSuccess implementation of time slept, a classic time picker is used, with separate scrolls for hours and minutes. Is yours minutes only?

**Comment by dariosalviwork** [comment] 2016-05-04 10:03
it's a selector of number of hours and minutes spent.
I've already implemented it. I will do a pull request soon.

**Closed** 2016-08-25 18:57 UTC
